defaults:
  - base

family: gpt2_loop
n_layer: 1
repeat_positional: true
repeat_ln: true
curriculum:
  loops:
    type: linear
    start: 15
    end: 30
    inc: 2
    interval: 500
n_loop_window: 15
n_loops: ${.curriculum.loops.start}
keep_n_tokens: null
token_dec: null