batch_size: 64
n_epoch: 15 # for infinite datasets, used only for more frequent evaluation
train_steps: 5000
eval_steps: 500

learning_rate: 0.0002
weight_decay: 0.0
save_every_steps: 10000
curriculum:
  dims:
    type: linear
    start: 1
    end: 10
    inc: 1
    interval: 3000
  points:
    type: linear
    start: 5
    end: 20
    inc: 2
    interval: 3000