batch_size: 64
n_epoch: 50 # for infinite datasets, used only for more frequent evaluation
train_steps: 10000
eval_steps: 1000

learning_rate: 0.0001
weight_decay: 0.0
save_every_steps: 10000
curriculum:
  dims:
    type: linear
    start: 5
    end: 20
    inc: 1
    interval: 5000
  points:
    type: linear
    start: 11
    end: 41
    inc: 2
    interval: 5000