wandb:
    project: looped-transformer
    log_every_steps: 100

gpu:
    cuda: True

model:
    family: gpt2
    n_embd: 256
    n_layer: 12
    n_head: 8
    n_dims: 20
    n_positions: 101
    # GPT-2 defaults
    dropout: 0.0
    bias: True


task_name: linear_regression
task:
    n_points: 30
    n_dim: 20
    std: 0.1
    sparsity: null

training:
    batch_size: 64
    
    learning_rate: 0.0001
    weight_decay: 0.0
    train_steps: 500000
    save_every_steps: 1000
    keep_every_steps: 100000
    curriculum:
        dims:
            start: 5
            end: 20
            inc: 1
            interval: 5000
        points:
            start: 11
            end: 41
            inc: 2
            interval: 5000
        loops:
            start: 1
            end: 1
            inc: 2
            interval: 500
    n_loop_window: 20

out_dir: ./results/linear_regression_baseline
debug_mode: False