device: cuda
debug_mode: False
random_seed: 1

defaults:
    - model: base
    - tasks: LR
    - training: base
    - _self_

wandb:
    enabled: False
    project: looped-transformer
    name: null
    log_every_steps: 50

out_dir: ./results/${tasks.task_name}/${model.family}/

hydra:
    output_subdir: null