device: cuda
debug_mode: False
random_seed: 1

defaults:
    - model: base
    - task: LR
    - training: base
    - _self_

wandb:
    enabled: False
    project: looped-transformer
    name: null
    log_every_steps: 50

out_dir: ./results/${task.task_name}/${model.family}/${now:%Y-%m-%d_%H-%M-%S}

hydra:
    run:
        dir: ${out_dir}